### ISSUE TITLE
找不到配置文件在哪里,无法添加Curseforge API Key

### ISSUE THREAD

**Issue by XC084** [jie65535/mirai-console-jcf-plugin#12]
/jcf setApiKey 命令不存在,
随后寻找配置文件无果,
在/config文件夹内没有找到jcf的配置文件.

**Comment by jie65535** [comment]
你确定插件正确加载了？请发一下插件的加载日志。

配置文件的话，目录是`./config/top.jie65535.jcf/JCurseforgeConfig.yml`

**Comment by XC084** [comment]
确认插件正确加载:
```
2023-06-27 18:17:21 I/plugin: Successfully loaded plugin J Curseforge Util v0.1.1
2023-06-27 18:17:22 I/J Curseforge Util: Plugin loaded
```
在自用bot上的完整启动过程在这里[log.txt](https://github.com/jie65535/mirai-console-jcf-plugin/files/11880715/log.txt)
为排除插件冲突问题在没有登录和只使用必要插件
1. chat-command-0.5.1.mirai.jar
2. mcl-addon-2.1.1.jar
3. mirai-api-http-2.9.1.mirai2.jar
4. mirai-console-jcf-plugin-0.1.1.mirai.jar
的启动过程在这里[test-log.txt](https://github.com/jie65535/mirai-console-jcf-plugin/files/11880759/test-log.txt)
二者均没有生成配置文件(寻找了config和data)
均可使用`/jcf help`指令,除了搜索功能会报错一切正常(废话,没配置当然报错
[jcf-ss-工作台.txt](https://github.com/jie65535/mirai-console-jcf-plugin/files/11880928/jcf-ss-.txt)

#怀疑是版本问题,曾根据[教程](https://mirai.mamoe.net/topic/2061/%E6%95%99%E7%A8%8B-%E7%94%A8mcl%E5%8D%87%E7%BA%A7mirai%E5%88%B0%E9%A2%84%E5%8F%91%E8%A1%8C%E7%89%88-%E6%93%8D%E4%BD%9C%E7%A4%BA%E4%BE%8B)升级到了2.15.0-m1

**Comment by jie65535** [comment]
我测试了一下，没有复现。
而且这个异常也不是API Key的问题，好像是找不到 [addons-ecs.forgesvc.net](https://addons-ecs.forgesvc.net/) 域名。
另外，在Curseforge中通常用来搜索模组和整合包，并且要用英文名，不能用中文。
中文的话建议用mcmod插件。

你可以多试几次，例如查找机械动力模组 `cfmod create`，我怀疑和网络问题有关。
另外，关于配置文件没创建的，建议重新确定，直接搜索配置文件的文件名，或者检查一下目录权限是否存在限制。

**Comment by XC084** [comment]
好吧,看上去确实是网络链接的问题,然后用了几个代理均没连上,决定放弃使用(之前也因为换代理连不上觉得是没配置的问题)

#但是,配置文件确实没有创建,这里是everything的搜索结果
![MMJAB)$1PDS%2FAUIEA8)AW](https://github.com/jie65535/mirai-console-jcf-plugin/assets/99209606/2960041a-9325-4aea-9120-4b65ae417a68)
![6186W% F04RY9QXR$}U2F$Q](https://github.com/jie65535/mirai-console-jcf-plugin/assets/99209606/0c226d70-50f8-44a7-8bd5-9c0b9c27b200)
在单独测试中也没有出现配置文件
![U(3JL9VJ9VYGY$2F@JDS66](https://github.com/jie65535/mirai-console-jcf-plugin/assets/99209606/e435bbb6-c689-4dd9-83bc-60e291600a87)
(因为没有其他电脑所以在mirai-android测了一下也没有生成配置文件(加载正常))
使用其他插件(包括您的jcc,jcr等)均有配置文件,所以应该也和目录权限无关.
既然无法复现(而且看起来别人也没有遇到同类问题)我也确实无法使用,就这样结束吧(

**Comment by jie65535** [comment]
额...  我好像知道原因了，我没有发布新版本插件的构建...  实际上最新版本是v1.1.0的，而不是v0.1.1...

**Comment by jie65535** [comment]
非常抱歉，我以为没有人用这个插件了... 你暂时先用这个，晚点我调整一下代码再发Release
[mirai-console-jcf-plugin-1.1.0.mirai2.jar.zip](https://github.com/jie65535/mirai-console-jcf-plugin/files/11891686/mirai-console-jcf-plugin-1.1.0.mirai2.jar.zip)

**Comment by XC084** [comment]
感谢,已经成功使用
